repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.7.1  # Use the latest version from https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml


  - repo: local
    rev: v1.0.0
    hooks:
      - id: bashate
        name: Bashate
        entry: bashate
        language: system
        types: [shell]
        files: \.sh$

